use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::{collections::BTreeMap, fs, io, path::{Path, PathBuf}};
use thiserror::Error;
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)] pub struct StableId(String);
impl StableId { pub fn new(value: impl Into<String>) -> Result<Self, String> { let value = value.into(); if value.is_empty() || !value.contains(':') { return Err(format!("stable ID must use namespace:name, got {value:?}")); } Ok(Self(value)) } pub fn as_str(&self) -> &str { &self.0 } }
#[derive(Debug, Error)] pub enum ContentError { #[error("failed to enumerate content directory {path}: {source}")] ReadDir { path: PathBuf, source: io::Error }, #[error("failed to read content file {path}: {source}")] Read { path: PathBuf, source: io::Error }, #[error("invalid JSON in content file {path}: {source}")] Json { path: PathBuf, source: serde_json::Error }, #[error("content file {path} has invalid stable id: {reason}")] Id { path: PathBuf, reason: String } }
#[derive(Clone, Debug, Serialize, Deserialize)] pub struct ContentRecord { pub id: StableId, #[serde(flatten)] pub fields: BTreeMap<String, Value> }
#[derive(Clone, Debug, Default)] pub struct Registry { records: BTreeMap<StableId, ContentRecord> }
impl Registry { pub fn insert(&mut self, record: ContentRecord) { self.records.insert(record.id.clone(), record); } pub fn get(&self, id: &StableId) -> Option<&ContentRecord> { self.records.get(id) } pub fn iter(&self) -> impl Iterator<Item = (&StableId, &ContentRecord)> { self.records.iter() } pub fn len(&self) -> usize { self.records.len() } }
pub fn load_json_registry(root: &Path) -> Result<Registry, ContentError> { let mut files = Vec::new(); collect_json(root, &mut files)?; files.sort(); let mut registry = Registry::default(); for path in files { let text = fs::read_to_string(&path).map_err(|source| ContentError::Read { path: path.clone(), source })?; let value: Value = serde_json::from_str(&text).map_err(|source| ContentError::Json { path: path.clone(), source })?; let id = value.get("id").and_then(Value::as_str).ok_or_else(|| ContentError::Id { path: path.clone(), reason: "missing string field id".into() })?; let id = StableId::new(id).map_err(|reason| ContentError::Id { path: path.clone(), reason })?; let fields = value.as_object().cloned().unwrap_or_default().into_iter().collect(); registry.insert(ContentRecord { id, fields }); } Ok(registry) }
fn collect_json(root: &Path, output: &mut Vec<PathBuf>) -> Result<(), ContentError> { if !root.exists() { return Ok(()); } for entry in fs::read_dir(root).map_err(|source| ContentError::ReadDir { path: root.to_path_buf(), source })? { let path = entry.map_err(|source| ContentError::ReadDir { path: root.to_path_buf(), source })?.path(); if path.is_dir() { collect_json(&path, output)?; } else if path.extension().and_then(|x| x.to_str()) == Some("json") { output.push(path); } } Ok(()) }
